// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFieldsResponse(arg1) {
  return window['go']['handlers']['FieldsResponseHandler']['DeleteFieldsResponse'](arg1);
}

export function GetAllFieldsResponses() {
  return window['go']['handlers']['FieldsResponseHandler']['GetAllFieldsResponses']();
}

export function GetFieldsResponse(arg1) {
  return window['go']['handlers']['FieldsResponseHandler']['GetFieldsResponse'](arg1);
}

export function GetFieldsResponseByFlowID(arg1) {
  return window['go']['handlers']['FieldsResponseHandler']['GetFieldsResponseByFlowID'](arg1);
}

export function InsertFieldsResponse(arg1) {
  return window['go']['handlers']['FieldsResponseHandler']['InsertFieldsResponse'](arg1);
}

export function UpdateFieldsResponse(arg1) {
  return window['go']['handlers']['FieldsResponseHandler']['UpdateFieldsResponse'](arg1);
}
