// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {flowfieldsresponse} from '../models';

export function DeleteFieldsResponse(arg1:string):Promise<void>;

export function GetAllFieldsResponses():Promise<any>;

export function GetFieldsResponse(arg1:string):Promise<flowfieldsresponse.FlowFieldsResponse>;

export function GetFieldsResponseByFlowID(arg1:string):Promise<any>;

export function InsertFieldsResponse(arg1:flowfieldsresponse.FlowFieldsResponse):Promise<flowfieldsresponse.FlowFieldsResponse>;

export function UpdateFieldsResponse(arg1:flowfieldsresponse.FlowFieldsResponse):Promise<void>;
