// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {file} from '../models';

export function GetFilePath():Promise<string>;

export function ParseToCsv(arg1:any):Promise<file.FileOutput>;

export function ReadFile(arg1:string):Promise<string>;
