// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ParseToCsv(arg1) {
  return window['go']['handlers']['FileHandler']['ParseToCsv'](arg1);
}

export function ReadCSVFile(arg1) {
  return window['go']['handlers']['FileHandler']['ReadCSVFile'](arg1);
}
