// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {flow} from '../models';

export function DeleteFlow(arg1:string):Promise<void>;

export function GetAllFlows():Promise<any>;

export function GetFlow(arg1:string):Promise<flow.Flow>;

export function InsertFlow(arg1:flow.Flow):Promise<flow.Flow>;

export function UpdateFlow(arg1:flow.Flow):Promise<void>;
