// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFlow(arg1) {
  return window['go']['handlers']['FlowHandler']['DeleteFlow'](arg1);
}

export function GetAllFlows() {
  return window['go']['handlers']['FlowHandler']['GetAllFlows']();
}

export function GetFlow(arg1) {
  return window['go']['handlers']['FlowHandler']['GetFlow'](arg1);
}

export function InsertFlow(arg1) {
  return window['go']['handlers']['FlowHandler']['InsertFlow'](arg1);
}

export function UpdateFlow(arg1) {
  return window['go']['handlers']['FlowHandler']['UpdateFlow'](arg1);
}
