// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {operation} from '../models';
import {json} from '../models';

export function DeleteOperationSchema(arg1:string):Promise<void>;

export function GetAllOperationSchema():Promise<any>;

export function GetAllSchemasWithTemplates():Promise<any>;

export function GetOperationSchema(arg1:string):Promise<operation.Operation>;

export function InsertOperationSchema(arg1:operation.Operation):Promise<operation.Operation>;

export function TestRequest(arg1:operation.Operation):Promise<json.RawMessage>;

export function UpdateOperationSchema(arg1:operation.Operation):Promise<void>;
