// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteOperationTemplate(arg1) {
  return window['go']['handlers']['OperationTemplateHandler']['DeleteOperationTemplate'](arg1);
}

export function GetAllKeysOperationTemplates(arg1) {
  return window['go']['handlers']['OperationTemplateHandler']['GetAllKeysOperationTemplates'](arg1);
}

export function GetAllOperationTemplates() {
  return window['go']['handlers']['OperationTemplateHandler']['GetAllOperationTemplates']();
}

export function GetOperationTemplate(arg1) {
  return window['go']['handlers']['OperationTemplateHandler']['GetOperationTemplate'](arg1);
}

export function InsertOperationTemplate(arg1) {
  return window['go']['handlers']['OperationTemplateHandler']['InsertOperationTemplate'](arg1);
}

export function UpdateOperationTemplate(arg1) {
  return window['go']['handlers']['OperationTemplateHandler']['UpdateOperationTemplate'](arg1);
}
