// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {operationparameter} from '../models';

export function DeleteOperationTemplate(arg1:string):Promise<void>;

export function GetAllKeysOperationTemplates(arg1:Array<string>):Promise<any>;

export function GetAllOperationTemplates():Promise<any>;

export function GetOperationTemplate(arg1:string):Promise<operationparameter.OperationParameter>;

export function InsertOperationTemplate(arg1:operationparameter.OperationParameter):Promise<operationparameter.OperationParameter>;

export function UpdateOperationTemplate(arg1:operationparameter.OperationParameter):Promise<void>;
