// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteOperationSchema(arg1) {
  return window['go']['handlers']['OperationSchemaHandler']['DeleteOperationSchema'](arg1);
}

export function GetAllOperationSchema() {
  return window['go']['handlers']['OperationSchemaHandler']['GetAllOperationSchema']();
}

export function GetAllSchemasWithTemplates() {
  return window['go']['handlers']['OperationSchemaHandler']['GetAllSchemasWithTemplates']();
}

export function GetOperationSchema(arg1) {
  return window['go']['handlers']['OperationSchemaHandler']['GetOperationSchema'](arg1);
}

export function InsertOperationSchema(arg1) {
  return window['go']['handlers']['OperationSchemaHandler']['InsertOperationSchema'](arg1);
}

export function TestRequest(arg1) {
  return window['go']['handlers']['OperationSchemaHandler']['TestRequest'](arg1);
}

export function UpdateOperationSchema(arg1) {
  return window['go']['handlers']['OperationSchemaHandler']['UpdateOperationSchema'](arg1);
}
