// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {process} from '../models';

export function CreateProcess(arg1:process.Process):Promise<process.Process>;

export function DeleteProcess(arg1:string):Promise<void>;

export function GetAllProcesses():Promise<any>;

export function GetProcess(arg1:string):Promise<process.Process>;

export function StartProcess(arg1:process.Process):Promise<process.Process>;

export function UpdateProcess(arg1:process.Process):Promise<void>;
