// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProcess(arg1) {
  return window['go']['handlers']['ProcessHandler']['CreateProcess'](arg1);
}

export function DeleteProcess(arg1) {
  return window['go']['handlers']['ProcessHandler']['DeleteProcess'](arg1);
}

export function GetAllProcesses() {
  return window['go']['handlers']['ProcessHandler']['GetAllProcesses']();
}

export function GetProcess(arg1) {
  return window['go']['handlers']['ProcessHandler']['GetProcess'](arg1);
}

export function StartProcess(arg1) {
  return window['go']['handlers']['ProcessHandler']['StartProcess'](arg1);
}

export function UpdateProcess(arg1) {
  return window['go']['handlers']['ProcessHandler']['UpdateProcess'](arg1);
}
